version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      # - pip install -r requirements.txt  # Example for a Python project
  pre_build:
    commands:
      - echo Pre-build started on `date`
  build:
    commands:
      - echo Build started on `date`
      - echo Running unit tests...
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging artifacts...
      - zip -r my-app.zip .
artifacts:
  files:
    - my-app.zip
  discard-paths: yes
