name: Terraform Workflow
'on':
  push:
    branches:
      - develop
env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
  AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
  AWS_SESSION_TOKEN: '${{ secrets.AWS_SESSION_TOKEN }}'
  BUCKET_TF_STATE: '${{ secrets.BUCKET_TF_STATE }}'
  TF_STATE_LOCK_TABLE: '${{ secrets.TF_STATE_LOCK_TABLE }}'
  AWS_REGION: eu-west-1
jobs:
  terraform:
    name: Terraform Infrastructure Change Management
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.BUCKET_TF_STATE }}" \
                            -backend-config="terraformstate/state-bucket" \
                            -backend-config="region=${{ env.AWS_REGION }}" \
                            -backend-config="dynamodb_table=${{ env.TF_STATE_LOCK_TABLE }}" \
                            -backend-config="encrypt=true"
      - name: Terraform Workspace select
        run: terraform workspace select dev
      - name: Terraform Format Check
        run: terraform fmt -check
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
      # - name: Terraform Plan Status
      #   if: steps.plan.outcome == 'failure'
      #   run: exit 1
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false